export const areaTagdata = [
	{
		label: "REACTION AREA",
		tags: [
			{
				tag: "FCV-1005",
				description: "G1-207A FLOW",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "FCV-1006",
				description: "G1-207B FLOW",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "FCV-1007",
				description: "G1-207C FLOW",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "FCV-1101",
				description: "FEED FLOW TO D1-301",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "FCV-1000",
				description: "CATALYST FLOW TO FMD",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "LCV-1219",
				description: "F1-430 LEVEL",
				dcsSignal: "",
				opening: "",
			},
		],
	},
	{
		label: "SRU/FILTRATION AREA",
		tags: [
			{
				tag: "LCV-1353",
				description: "F1-408 LEVEL",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "LCV-1355",
				description: "F1-411A LEVEL",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "FCV-1371",
				description: "FLOW TO M1-521/F1-511",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "FCV-1350",
				description: "SOLVENT WASH TO ROVAC-A",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "LCV-1777",
				description: "F1-411B LEVEL",
				dcsSignal: "",
				opening: "",
			},
		],
	},
	{
		label: "PAC/DRYER AREA",
		tags: [
			{
				tag: "FCV-1425",
				description: "CG FLOW TO P1-902A/B",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "PCV-1430",
				description: "STEAM PRESSURE TO M1-423",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "H1-857",
				description: "STEAM PRESSURE",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "PCV-1437",
				description: "DRYER GAS PRESSURE",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "FCV-1529",
				description: "SOLVENT FLOW TO D1-501",
				dcsSignal: "",
				opening: "",
			},
		],
	},
	{
		label: "CRU AREA",
		tags: [
			{
				tag: "FCV-10014",
				description: "RESIDUE FLOW TO F1-705",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "PCV-10022",
				description: "G1-706 A/B K.B",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "FCV-10012",
				description: "CHILLED WATER TO F1-705",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "LCV-10026",
				description: "DMW TO F1-722",
				dcsSignal: "",
				opening: "",
			},
			{
				tag: "FCV-10068",
				description: "FEED TO FIL-707-A",
				dcsSignal: "",
				opening: "",
			},
		],
	},
];
export const operators = [
	"Pardeep Kumar",
	"Shoaib Shah",
	"Parvez Ali",
	"Javeria Tariq",
	"Sahil Mazari",
	"Ali Raza",
	"Raza Ali",
	"Sajid Ali",
	"Salman Ali",
	"Sohail Ahmed",
	"Sarfaraz Ahmed",
	"Saqib Ali",
];
export const equipmentWaterSupplyData = [
	{
		serialNo: "1",
		equipmentNo: "G1-207 A",
		inletFlow: "FG-3463-A, 1% = 10 kg/hr",
		outletFlow: "FG-3463-B, 1% = 10 kg/hr",
	},
	{
		serialNo: "2",
		equipmentNo: "G1-207 B",
		inletFlow: "FG-3464-A, 1% = 10 kg/hr",
		outletFlow: "FG-3464-B, 1% = 10 kg/hr",
	},
	{
		serialNo: "3",
		equipmentNo: "G1-207 C",
		inletFlow: "FG-3465-A, 1% = 10 kg/hr",
		outletFlow: "FG-3465-B, 1% = 10 kg/hr",
	},
	{
		serialNo: "4",
		equipmentNo: "G1-444",
		inletFlow: "FG-3769B, 1% = 10 kg/hr",
		outletFlow: "FG-3466-B, 1% = 10 kg/hr",
	},
	{
		serialNo: "5",
		equipmentNo: "G1-402",
		inletFlow: "FG-3511, 0 - 1000 kg/hr",
		outletFlow: "FG-3467-A, 1% = 10 kg/hr",
	},
	{
		serialNo: "6",
		equipmentNo: "G1-403",
		inletFlow: "FG-3510, 0 - 1000 kg/hr",
		outletFlow: "FG-3466-A, 1% = 10 kg/hr",
	},
	{
		serialNo: "7",
		equipmentNo: "G1-407 A",
		inletFlow: "FG-3468-B, 1% = 4 kg/hr",
		outletFlow: "FG-3468-A, 1% = 4 kg/hr",
	},
	{
		serialNo: "8",
		equipmentNo: "G1-407 B",
		inletFlow: "FG-3472-B, 1% = 4 kg/hr",
		outletFlow: "FG-3469-A, 1% = 4 kg/hr",
	},
	{
		serialNo: "9",
		equipmentNo: "G1-409 A",
		inletFlow: "FG-3470-B, 1% = 4 kg/hr",
		outletFlow: "FG-3470-A, 1% = 4 kg/hr",
	},
	{
		serialNo: "10",
		equipmentNo: "G1-409 B",
		inletFlow: "FG-3480-B, 0 - 600 kg/hr",
		outletFlow: "FG-3480-A, 0 - 600 kg/hr",
	},
	{
		serialNo: "11",
		equipmentNo: "G1-412 A",
		inletFlow: "FG-3472-A, 0 - 600 kg/hr",
		outletFlow: "FG-3512-B, 0 - 600 kg/hr",
	},
	{
		serialNo: "12",
		equipmentNo: "G1-412 B",
		inletFlow: "FG-3476-B, 1% = 1.6 kg/hr",
		outletFlow: "FG-3480-B, 1% = 1.6 kg/hr",
	},
	{
		serialNo: "13",
		equipmentNo: "G1-416 A",
		inletFlow: "FG-3474-A, 1% = 6 kg/hr",
		outletFlow: "FG-3474-B, 1% = 6 kg/hr",
	},
	{
		serialNo: "14",
		equipmentNo: "G1-416 B",
		inletFlow: "FG-3471-B, 1% = 4 kg/hr",
		outletFlow: "FG-3471-A, 1% = 4 kg/hr",
	},
	{
		serialNo: "15",
		equipmentNo: "G1-418 A",
		inletFlow: "FG-3476-A, 0 - 600 kg/hr",
		outletFlow: "FG-3476-B, 0 - 600 kg/hr",
	},
	{
		serialNo: "16",
		equipmentNo: "G1-418 B",
		inletFlow: "FG-3477-A, 0 - 600 kg/hr",
		outletFlow: "FG-3477-B, 0 - 600 kg/hr",
	},
	{
		serialNo: "17",
		equipmentNo: "G1-505 A",
		inletFlow: "FG-3371-B, 1% = 10 kg/hr",
		outletFlow: "FG-3372-A, 1% = 10 kg/hr",
	},
	{
		serialNo: "18",
		equipmentNo: "G1-505 B",
		inletFlow: "FG-3372-B, 1% = 10 kg/hr",
		outletFlow: "FG-3371-A, 1% = 10 kg/hr",
	},
	{
		serialNo: "19",
		equipmentNo: "G1-507 A",
		inletFlow: "FG-3478-A, 0 - 600 kg/hr",
		outletFlow: "FG-3478-B, 0 - 600 kg/hr",
	},
	{
		serialNo: "20",
		equipmentNo: "G1-507 B",
		inletFlow: "FG-3479-A, 0 - 600 kg/hr",
		outletFlow: "FG-3479-B, 0 - 600 kg/hr",
	},
	{
		serialNo: "21",
		equipmentNo: "G1-509 A",
		inletFlow: "FG-3476-A, 1% = 6 kg/hr",
		outletFlow: "FG-3475-B, 1% = 6 kg/hr",
	},
	{
		serialNo: "22",
		equipmentNo: "G1-509 B",
		inletFlow: "FG-3481-A, 0 - 600 kg/hr",
		outletFlow: "FG-3481-B, 0 - 600 kg/hr",
	},
	{
		serialNo: "23",
		equipmentNo: "G1-511",
		inletFlow: "FG-3482-A, 1% = 6 kg/hr",
		outletFlow: "FG-3482-B, 1% = 6 kg/hr",
	},
	{
		serialNo: "24",
		equipmentNo: "G1-512 A",
		inletFlow: "FG-3483-B, 1% = 4 kg/hr",
		outletFlow: "FG-3483-B, 1% = 0.27 kg/hr",
	},
	{
		serialNo: "25",
		equipmentNo: "G1-512 B",
		inletFlow: "FG-3484-A, 1% = 4 kg/hr",
		outletFlow: "FG-3483-A, 1% = 4 kg/hr",
	},
	{
		serialNo: "26",
		equipmentNo: "G1-515",
		inletFlow: "",
		outletFlow: "FG-3469-B, 1% = 4 kg/hr",
	},
	{
		serialNo: "27",
		equipmentNo: "G1-516",
		inletFlow: "FG-3485-A, 1% = 6 kg/hr",
		outletFlow: "FG-3485-B, 1% = 6 kg/hr",
	},
	{
		serialNo: "28",
		equipmentNo: "G1-530 A",
		inletFlow: "FG-3526-A, 1% = 4 kg/hr",
		outletFlow: "FG-3526-B, 1% = 4 kg/hr",
	},
	{
		serialNo: "29",
		equipmentNo: "G1-530 B",
		inletFlow: "FG-3527-A, 1% = 4 kg/hr",
		outletFlow: "FG-3527-B, 1% = 4 kg/hr",
	},
	{
		serialNo: "30",
		equipmentNo: "G1-604 A",
		inletFlow: "FG-3486-A, 1% = 4 kg/hr",
		outletFlow: "FG-3486-A, 1% = 4 kg/hr",
	},
	{
		serialNo: "31",
		equipmentNo: "G1-604 B",
		inletFlow: "FG-3487-A, 1% = 4 kg/hr",
		outletFlow: "FG-3487-B, 1% = 4 kg/hr",
	},
	{
		serialNo: "32",
		equipmentNo: "G1-606 A",
		inletFlow: "FG-3488-A, 1% = 6 kg/hr",
		outletFlow: "FG-3488-B, 1% = 6 kg/hr",
	},
	{
		serialNo: "33",
		equipmentNo: "G1-606 B",
		inletFlow: "FG-3489-A, 1% = 6 kg/hr",
		outletFlow: "FG-3489-B, 1% = 6 kg/hr",
	},
	{
		serialNo: "34",
		equipmentNo: "G1-607 A",
		inletFlow: "FG-3491-B, 1% = 6 kg/hr",
		outletFlow: "FG-3491-A, 1% = 6 kg/hr",
	},
	{
		serialNo: "35",
		equipmentNo: "G1-607 B",
		inletFlow: "FG-3490-A, 1% = 6 kg/hr",
		outletFlow: "FG-3490-B, 1% = 6 kg/hr",
	},
	{
		serialNo: "36",
		equipmentNo: "G1-1606 A",
		inletFlow: "FG-3504-A, 1% = 6 kg/hr",
		outletFlow: "FG-3479-A, 1% = 6 kg/hr",
	},
	{
		serialNo: "37",
		equipmentNo: "G1-1606 B",
		inletFlow: "FG-3505-A, 1% = 4 kg/hr",
		outletFlow: "FG-3504-B, 1% = 4 kg/hr",
	},
];

export const equipmentData = [
	{
		label: "REACTION AREA",
		equipments: [
			{ equipment: "G1-703", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-318", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-436", stopped: "", started: "", remarks: "" },
			{ equipment: "C1-331", stopped: "", started: "", remarks: "" },
			{ equipment: "C1-830", stopped: "", started: "", remarks: "" },
		],
	},
	{
		label: "SOLVENT RECOVERY AREA",
		equipments: [
			{ equipment: "G1-507", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-509", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-530", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-604", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-606", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-607", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-615", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-630", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-632", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-650", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-1606", stopped: "", started: "", remarks: "" },
		],
	},
	{
		label: "PAC AREA",
		equipments: [
			{ equipment: "C1-503", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-505", stopped: "", started: "", remarks: "" },
		],
	},
	{
		label: "CRU AREA",
		equipments: [
			{ equipment: "G1-706", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-709", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-713", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-720", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-723", stopped: "", started: "", remarks: "" },
			{ equipment: "G1-731", stopped: "", started: "", remarks: "" },
		],
	},
];
export const safetyShowersData = {
	safetyShowers: [
		{
			location: "Ground Floor Reaction",
			no: 5,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "Ground Floor Reaction",
			no: 6,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "Ground Floor Reaction",
			no: 7,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "Ground Floor Reaction",
			no: 8,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "Ground Floor Reaction",
			no: 9,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "First Floor Reaction",
			no: 10,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "First Floor Reaction",
			no: 11,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "First Floor Reaction",
			no: 12,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "2nd Floor Reaction",
			no: 13,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "2nd Floor Reaction",
			no: 14,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "2nd Floor Reaction",
			no: 15,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "3rd Floor Reaction",
			no: 16,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "3rd Floor Reaction",
			no: 17,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "3rd Floor Reaction",
			no: 18,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "4rth Floor Reaction",
			no: 19,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "4rth Floor Reaction",
			no: 20,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "Ground Floor Sol. Recovery",
			no: 21,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "First Floor Sol. Recovery",
			no: 22,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "2nd Floor Sol. Recovery",
			no: 23,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "3rd Floor Sol. Recovery",
			no: 24,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "4rth Floor Sol. Recovery",
			no: 25,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "Ground Floor TA Dryer",
			no: 26,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "Ground Floor Rovac",
			no: 27,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "First Floor Rovac",
			no: 28,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "2nd Floor Rovac",
			no: 29,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "3rd Floor Rovac",
			no: 30,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "Ground Floor T.O",
			no: 31,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "Top Floor T.O",
			no: 32,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "Ground Floor T.O",
			no: 33,
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "Ground Floor CRU",
			no: "",
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
		{
			location: "2nd Floor CRU",
			no: "",
			leakage: false,
			bulbOk: false,
			pressureOk: false,
		},
	],
	fireExtinguishers: [
		{ location: "03-Reaction Area", pressureOk: false, boxOk: false },
		{ location: "36-Reaction Area", pressureOk: false, boxOk: false },
		{ location: "65-Reaction Area", pressureOk: false, boxOk: false },
		{ location: "50-Reaction Area", pressureOk: false, boxOk: false },
		{ location: "47-Reaction Area", pressureOk: false, boxOk: false },
		{ location: "42-Fin Fan Area", pressureOk: false, boxOk: false },
		{ location: "45-Rovac Area", pressureOk: false, boxOk: false },
		{ location: "46-Rovac Area", pressureOk: false, boxOk: false },
		{ location: "41-Rovac Area", pressureOk: false, boxOk: false },
		{ location: "40-Dryer Area", pressureOk: false, boxOk: false },
		{ location: "37-Gr.Floor Solv Recovery", pressureOk: false, boxOk: false },
		{ location: "44-Gr.Floor Solv Recovery", pressureOk: false, boxOk: false },
		{ location: "34-1st.Floor Solv Recovery", pressureOk: false, boxOk: false },
		{
			location: "36-2nd .Floor Solv Recovery",
			pressureOk: false,
			boxOk: false,
		},
		{
			location: "12-3rd .Floor Solv Recovery",
			pressureOk: false,
			boxOk: false,
		},
		{
			location: "13-4th .Floor Solv Recovery",
			pressureOk: false,
			boxOk: false,
		},
		{ location: "NIL_Core Out St. CO2", pressureOk: false, boxOk: false },
		{ location: "NIL_Core Out St. CO2", pressureOk: false, boxOk: false },
		{ location: "NIL_Core Out St. CO2", pressureOk: false, boxOk: false },
		{ location: "NIL_Core Out St. CO2", pressureOk: false, boxOk: false },
		{ location: "03-Gr-Floor T.O", pressureOk: false, boxOk: false },
		{ location: "64-1st-Floor T.O", pressureOk: false, boxOk: false },
		{ location: "57-2nd Floor T.O", pressureOk: false, boxOk: false },
		{ location: "16-3rdFloor T.O", pressureOk: false, boxOk: false },
		{ location: "63-4th Floor T.O", pressureOk: false, boxOk: false },
		{ location: "63-4th Floor T.O", pressureOk: false, boxOk: false },
		{ location: "54-5th Floor T.O", pressureOk: false, boxOk: false },
		{ location: "Nil- Ground Floor CRU", pressureOk: false, boxOk: false },
		{ location: "Nil - 1st Floor CRU", pressureOk: false, boxOk: false },
		{ location: "Nil - 2nd Floor CRU", pressureOk: false, boxOk: false },
		{ location: "Nil - 3rd Floor CRU", pressureOk: false, boxOk: false },
	],
	escapeSets: [
		{ location: "12&7-Reaction 1st floor", pressureOk: false, boxOk: false },
		{ location: "28-Reaction 1st floor", pressureOk: false, boxOk: false },
		{ location: "11&1-Reaction 2nd floor", pressureOk: false, boxOk: false },
		{ location: "08&5-Reaction 2nd floor", pressureOk: false, boxOk: false },
		{ location: "05-Reaction 3rd floor", pressureOk: false, boxOk: false },
		{ location: "10&2-Reaction 3rd floor", pressureOk: false, boxOk: false },
		{ location: "07-Reaction 4th floor", pressureOk: false, boxOk: false },
		{ location: "06&8-Reaction 4th floor", pressureOk: false, boxOk: false },
		{ location: "32-Reaction 5th floor", pressureOk: false, boxOk: false },
		{ location: "04&8-Reaction 5th floor", pressureOk: false, boxOk: false },
		{ location: "10&13-South Fin fans", pressureOk: false, boxOk: false },
		{ location: "40-North Fin Fan", pressureOk: false, boxOk: false },
		{ location: "34&19-3rd Floor Rovac", pressureOk: false, boxOk: false },
		{ location: "47&18-3rd Floor Rovac", pressureOk: false, boxOk: false },
		{ location: "01&13-2nd Floor Rovac", pressureOk: false, boxOk: false },
		{ location: "49-1st Floor Rovac", pressureOk: false, boxOk: false },
		{ location: "59-1st Floor Rovac", pressureOk: false, boxOk: false },
		{
			location: "15&26-Ist Floor Sol. Recovery",
			pressureOk: false,
			boxOk: false,
		},
		{ location: "17-2nd Floor Sol. Recovery", pressureOk: false, boxOk: false },
		{
			location: "9&28-3rd Floor Sol. Recovery",
			pressureOk: false,
			boxOk: false,
		},
		{ location: "25-4th Floor Sol.Recovery", pressureOk: false, boxOk: false },
		{ location: "16&25-Ist Floor MA col.", pressureOk: false, boxOk: false },
		{ location: "39-2nd Floor T.O", pressureOk: false, boxOk: false },
		{ location: "43&15-3rd Floor T.O", pressureOk: false, boxOk: false },
		{ location: "41-4th Floor T.O", pressureOk: false, boxOk: false },
		{ location: "51&16-5th Floor T.O", pressureOk: false, boxOk: false },
		{ location: "29&03-HPCCU top", pressureOk: false, boxOk: false },
		{ location: "30-HPCCU top", pressureOk: false, boxOk: false },
		{ location: "Nil - 1st Floor CRU", pressureOk: false, boxOk: false },
		{ location: "Nil - 2nd Floor CRU", pressureOk: false, boxOk: false },
		{ location: "Nil - 3rd Floor CRU", pressureOk: false, boxOk: false },
	],
};
export const safetyShowersData1 = {
	safetyShowers: [
		{
			location: "Ground Floor Reaction",
			no: 5,
		},
		{
			location: "Ground Floor Reaction",
			no: 6,
		},
		{
			location: "Ground Floor Reaction",
			no: 7,
		},
		{
			location: "Ground Floor Reaction",
			no: 8,
		},
		{
			location: "Ground Floor Reaction",
			no: 9,
		},
		{
			location: "First Floor Reaction",
			no: 10,
		},
		{
			location: "First Floor Reaction",
			no: 11,
		},
		{
			location: "First Floor Reaction",
			no: 12,
		},
		{
			location: "2nd Floor Reaction",
			no: 13,
		},
		{
			location: "2nd Floor Reaction",
			no: 14,
		},
		{
			location: "2nd Floor Reaction",
			no: 15,
		},
		{
			location: "3rd Floor Reaction",
			no: 16,
		},
		{
			location: "3rd Floor Reaction",
			no: 17,
		},
		{
			location: "3rd Floor Reaction",
			no: 18,
		},
		{
			location: "4rth Floor Reaction",
			no: 19,
		},
		{
			location: "4rth Floor Reaction",
			no: 20,
		},
		{
			location: "Ground Floor Sol. Recovery",
			no: 21,
		},
		{
			location: "First Floor Sol. Recovery",
			no: 22,
		},
		{
			location: "2nd Floor Sol. Recovery",
			no: 23,
		},
		{
			location: "3rd Floor Sol. Recovery",
			no: 24,
		},
		{
			location: "4rth Floor Sol. Recovery",
			no: 25,
		},
		{
			location: "Ground Floor TA Dryer",
			no: 26,
		},
		{
			location: "Ground Floor Rovac",
			no: 27,
		},
		{
			location: "First Floor Rovac",
			no: 28,
		},
		{
			location: "2nd Floor Rovac",
			no: 29,
		},
		{
			location: "3rd Floor Rovac",
			no: 30,
		},
		{
			location: "Ground Floor T.O",
			no: 31,
		},
		{
			location: "Top Floor T.O",
			no: 32,
		},
		{
			location: "Ground Floor T.O",
			no: 33,
		},
		{
			location: "Ground Floor CRU",
			no: null,
		},
		{
			location: "2nd Floor CRU",
			no: null,
		},
	],
	fireExtinguishers: [
		{ location: "03-Reaction Area" },
		{ location: "36-Reaction Area" },
		{ location: "65-Reaction Area" },
		{ location: "50-Reaction Area" },
		{ location: "47-Reaction Area" },
		{ location: "42-Fin Fan Area" },
		{ location: "45-Rovac Area" },
		{ location: "46-Rovac Area" },
		{ location: "41-Rovac Area" },
		{ location: "40-Dryer Area" },
		{ location: "37-Gr.Floor Solv Recovery" },
		{ location: "44-Gr.Floor Solv Recovery" },
		{ location: "34-1st.Floor Solv Recovery" },
		{
			location: "36-2nd .Floor Solv Recovery",

			boxOk: false,
		},
		{
			location: "12-3rd .Floor Solv Recovery",

			boxOk: false,
		},
		{
			location: "13-4th .Floor Solv Recovery",

			boxOk: false,
		},
		{ location: "NIL_Core Out St. CO2" },
		{ location: "NIL_Core Out St. CO2" },
		{ location: "NIL_Core Out St. CO2" },
		{ location: "NIL_Core Out St. CO2" },
		{ location: "03-Gr-Floor T.O" },
		{ location: "64-1st-Floor T.O" },
		{ location: "57-2nd Floor T.O" },
		{ location: "16-3rdFloor T.O" },
		{ location: "63-4th Floor T.O" },
		{ location: "63-4th Floor T.O" },
		{ location: "54-5th Floor T.O" },
		{ location: "Nil- Ground Floor CRU" },
		{ location: "Nil - 1st Floor CRU" },
		{ location: "Nil - 2nd Floor CRU" },
		{ location: "Nil - 3rd Floor CRU" },
	],
	escapeSets: [
		{ location: "12&7-Reaction 1st floor" },
		{ location: "28-Reaction 1st floor" },
		{ location: "11&1-Reaction 2nd floor" },
		{ location: "08&5-Reaction 2nd floor" },
		{ location: "05-Reaction 3rd floor" },
		{ location: "10&2-Reaction 3rd floor" },
		{ location: "07-Reaction 4th floor" },
		{ location: "06&8-Reaction 4th floor" },
		{ location: "32-Reaction 5th floor" },
		{ location: "04&8-Reaction 5th floor" },
		{ location: "10&13-South Fin fans" },
		{ location: "40-North Fin Fan" },
		{ location: "34&19-3rd Floor Rovac" },
		{ location: "47&18-3rd Floor Rovac" },
		{ location: "01&13-2nd Floor Rovac" },
		{ location: "49-1st Floor Rovac" },
		{ location: "59-1st Floor Rovac" },
		{
			location: "15&26-Ist Floor Sol. Recovery",

			boxOk: false,
		},
		{ location: "17-2nd Floor Sol. Recovery" },
		{
			location: "9&28-3rd Floor Sol. Recovery",

			boxOk: false,
		},
		{ location: "25-4th Floor Sol.Recovery" },
		{ location: "16&25-Ist Floor MA col." },
		{ location: "39-2nd Floor T.O" },
		{ location: "43&15-3rd Floor T.O" },
		{ location: "41-4th Floor T.O" },
		{ location: "51&16-5th Floor T.O" },
		{ location: "29&03-HPCCU top" },
		{ location: "30-HPCCU top" },
		{ location: "Nil - 1st Floor CRU" },
		{ location: "Nil - 2nd Floor CRU" },
		{ location: "Nil - 3rd Floor CRU" },
	],
};

export const auditItemsData = [
	{
		description:
			"No unnecessary isolation tags are present in the area, and all threads have been removed",
	},
	{
		description: "All locks and chains have been placed in lock and chain box",
	},
	{ description: "Lock and chain box is properly sorted" },
	{ description: "All toolboxes are properly sorted" },
	{ description: "Valves keys are placed on valve key stands" },
	{ description: "Hammers are placed in hammer boxes" },
	{
		description: "Unnecessary barricade tapes have been removed from the area",
	},
	{ description: "Is there any mopping requirement on any of the skid" },
	{ description: "All laid hoses have been properly tape barricaded" },
	{ description: "There is no unnecessary scaffolding in the area" },
	{
		description:
			"Escape/ BA sets are placed in their designated locations and are not damaged",
	},
	{ description: "PVC suits are available in the designated location" },
	{ description: "Fire extinguishers are present at designated location" },
	{ description: "Hoses are properly placed on hose reels" },
	{
		description:
			"Unnecessary items e.g., tags, tools, gaskets, sample bottles, tagged stools etc. are not present in the area and are placed at designated location",
	},
];
